version: "3"
services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - --providers.docker
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=foo@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - back
      - front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl/:/letsencrypt/

  front:
    restart: unless-stopped
    image: wa_clt_front:rc14
    build:
      context: .
      dockerfile: front/Dockerfile
      args:
        BASE_DOMAIN: ${BASE_DOMAIN:-workadventure.localhost}

        START_ROOM_URL: "$START_ROOM_URL"
        JITSI_PRIVATE_MODE: "$JITSI_PRIVATE_MODE"
        JITSI_URL: "$JITSI_URL"
        START_ROOM_URL: "$START_ROOM_URL"
        TURN_PASSWORD: "$TURN_PASSWORD"
        TURN_SERVER: "$TURN_SERVER"
        TURN_USER: "$TURN_USER"
        STUN_SERVER: "$STUN_SERVER"
        MAX_PER_GROUP: "$MAX_PER_GROUP"
    labels:
      - "traefik.http.routers.front.rule=Host(`play.${BASE_DOMAIN:-workadventure.localhost}`)"
      - "traefik.http.routers.front.entryPoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=8000"
      - "traefik.http.routers.front-ssl.rule=Host(`play.${BASE_DOMAIN:-workadventure.localhost}`)"
      - "traefik.http.routers.front-ssl.entryPoints=websecure"
      - "traefik.http.routers.front-ssl.tls=true"
      - "traefik.http.routers.front-ssl.service=front"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"

  back:
    restart: unless-stopped
    image: wa_clt_back:rc6
    build:
      context: .
      dockerfile: back/Dockerfile
    environment:
      SECRET_KEY: "$SECRET_KEY"
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      JITSI_URL: "$JITSI_URL"
      JITSI_ISS: "$JITSI_ISS"
      MAX_PER_GROUP: "$MAX_PER_GROUP"
    labels:
      - "traefik.http.routers.back.rule=Host(`api.example.com`)"
      - "traefik.http.routers.back.entryPoints=web"
      - "traefik.http.services.back.loadbalancer.server.port=8080"
      - "traefik.http.routers.back-ssl.rule=Host(`api.example.com`)"
      - "traefik.http.routers.back-ssl.entryPoints=websecure"
      - "traefik.http.routers.back-ssl.tls=true"
      - "traefik.http.routers.back-ssl.service=back"
      - "traefik.http.routers.back.tls.certresolver=letsencrypt"

  pusher:
    restart: unless-stopped
    image: wa_clt_pusher:rc6
    build:
      context: .
      dockerfile: pusher/Dockerfile
    environment:
      SECRET_KEY: "$SECRET_KEY"
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      API_URL: back:50051
      JITSI_URL: "$JITSI_URL"
      JITSI_ISS: "$JITSI_ISS"
    labels:
      - "traefik.http.routers.pusher.rule=Host(`pusher.${BASE_DOMAIN:-workadventure.localhost}`)"
      - "traefik.http.routers.pusher.entryPoints=web"
      - "traefik.http.services.pusher.loadbalancer.server.port=8080"
      - "traefik.http.routers.pusher-ssl.rule=Host(`pusher.${BASE_DOMAIN:-workadventure.localhost}`)"
      - "traefik.http.routers.pusher-ssl.entryPoints=websecure"
      - "traefik.http.routers.pusher-ssl.tls=true"
      - "traefik.http.routers.pusher-ssl.service=pusher"
      - "traefik.http.routers.pusher.tls.certresolver=letsencrypt"
  
  maps:
    image: wa_clt_maps:rc4
    build:
      context: .
      dockerfile: maps/Dockerfile
    labels:
      - "traefik.http.routers.maps.rule=Host(`maps.${BASE_DOMAIN:-workadventure.localhost}`)"
      - "traefik.http.routers.maps.entryPoints=web"
      - "traefik.http.services.maps.loadbalancer.server.port=8000"
      - "traefik.http.routers.maps-ssl.rule=Host(`maps.${BASE_DOMAIN:-workadventure.localhost}`)"
      - "traefik.http.routers.maps-ssl.entryPoints=websecure"
      - "traefik.http.routers.maps-ssl.tls=true"
      - "traefik.http.routers.maps-ssl.service=maps"
      - "traefik.http.routers.maps.tls.certresolver=letsencrypt"
    volumes:
      - ./maps/:/usr/share/nginx/html/
